#NOTE: Not yet functional or complete: Work in progress
FROM ethereum/client-go:alpine
# Apline Linux
# Based on https://hub.docker.com/r/ethereum/client-go/~/dockerfile/
MAINTAINER Gary de Beer


#ADD ethereum /home/ubuntu/ethereum
VOLUME ["/BlockchainInfrastucture"]
WORKDIR /BlockchainInfrastucture

EXPOSE 20000
EXPOSE 20010

CMD ["./dockerStart.sh"]
